### ISSUE TITLE
 Fireball made with Polymer

### ISSUE THREAD

**Issue by nantas** [unbug/Polymer-notes#12]
- 项目名称：Fireball Game Editor
- 项目连接：[英文](http://fireball-x.com/en) [中文](http://fireball-x.com)
- 项目简介

>Fireball is a Hackable editor that combines power of full GUI toolset and popular open sourced game engine such as Pixi.js and Cocos2D-JS to create cross-platform mobile and HTML5 games.

>Fireball is an editor framework for game development. We focus on creating the most accessible and feature reach GUI toolset in one single editor with HTML and JavaScript. On the runtime side, Fireball uses other popular open sourced game engines such as Pixi.js and Cocos2D-JS. This makes Fireball really easy to get into for game engine users. Users will keep the benefit of all the features, packing and optimization of other game engines, but with a better editor much more can be achieved.

>The editor design is deeply inspired by Unity which we believe has the most advanced game developing editor at the moment. Fireball advances in editor and tool extendability thanks to modern Web technology. We use a combination of Polymer, Electron, Nodejs and plain-old HTML and CSS. Web developers can easily hack the editor and create tools that empowers your workflow in no time.

**Comment by nantas** [comment]
@unbug 请帮忙提交一下，非常感谢！

**Comment by unbug** [comment]
非常强大的项目！你能将哪里用到 Polymer 的技术详细描述一下吗？将Polymer的重量级位置突显出来，有一个演示视频更加的好。

**Comment by unbug** [comment]
我看到你的项目有github，如果上面有相关polymer 原源码的地方，补充上相关连接会非常好！

**Comment by unbug** [comment]
我看到你的网站上有twitter账号，也补上，如果他们有兴趣的话可能会跟你们交流。

**Comment by unbug** [comment]
麻烦你加我一下我的QQ 346742896
