### ISSUE TITLE
Polymer 应用推荐

### ISSUE THREAD

**Issue by renfeng** [unbug/Polymer-notes#15]
Project Name: Android SDK Web Manager (WebMgr)
Company: GDG Suzhou
Site: http://studyjams.dushu.hu/packages.html
Video: n/a
Summary: https://plus.google.com/+FrankR/posts/fHWCAi7Rsji

GDG Suzhou will bring it to GDG Global Summit
https://gdgdocs.org/presentation/d/1tEm-JweMHKUki4E14fteX9iZMXXqc-nIdrlq2Uow9lQ/edit#slide=id.g9a20617bb_0_64

**Comment by unbug** [comment]
hi,不得不说这个有点单薄，但我放到polymer-note里去了 ;)

**Comment by renfeng** [comment]
谢谢 :D
