### ISSUE TITLE
一个用 polymer 构建的 Android app 自动化测试中心

### ISSUE THREAD

**Issue by StuartLee** [unbug/Polymer-notes#16]
3. Test Platform for Android Apps
===================
- Project Name: Test Platform for Android Apps
- Company: Wandoulabs
- Site: Private
- Vidoe: [Test platform built with Polymer](https://www.youtube.com/watch?v=A51O3njdi8s)
- Summary: 

>*Test Platform* is an integrated series solutions designed specifically for the testify needs of engineers in *Wandou Labs*. Front end design and ports of this project enables developers in the lab to execute all sets of test tasks, including stability, response speed and compatibility, on real mobile phones of all available brands and all versions of released operating systems. 

>The front end design of *Test Platform* project utilizes *<core / paper elements>*  of ***Polymer*** and the visualization part of the page was achieved with *Highcharts* encapsulated in polymer web components. Today, the project have already been put online and widely used by developing groups among *Wandou Labs*.

**Comment by unbug** [comment]
已经添加！
